name: PR Comment and Review Notification

on:
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  notify_on_pr_comment_or_review:
    runs-on: ubuntu-latest
    if: github.event.issue.pull_request != null || github.event.pull_request != null
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install axios moment-timezone

      - name: Send Slack Notification
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GIT_TOKEN}}
          script: |
            const fs = require('fs')
            const path = require('path')
            
            const scriptPath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'scripts', 'pr-comment-notification.js')
            const script = fs.readFileSync(scriptPath, 'utf8')
            
            eval(script)
            
            await sendPRCommentNotification({
              webhook: process.env.SLACK_WEBHOOK_URL,
              context: context
            })
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.WEB_HOOK_URL }}