name: Slack Notification

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Custom message'
        required: true
      reviewers:
        description: 'Reviewers (comma-separated)'
        required: false

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install axios moment-timezone

      - name: Send Slack Notification
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GIT_TOKEN}}
          script: |
            const fs = require('fs')
            const path = require('path')
            
            const scriptPath = path.join(process.env.GITHUB_WORKSPACE, '.github', 'scripts', 'slack-notification.js')
            const script = fs.readFileSync(scriptPath, 'utf8')
            
            eval(script)
            
            const reviewers = '${{ github.event.inputs.reviewers }}'.split(',').filter(Boolean).map(r => r.trim())
            
            await sendSlackNotification({
              webhook: process.env.SLACK_WEBHOOK_URL,
              context: context,
              reviewers: reviewers,
              customMessage: '${{ github.event.inputs.message }}',
              isManualTrigger: '${{ github.event_name }}' === 'workflow_dispatch'
            })
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          TIMEZONE: 'Asia/Seoul'
          WORK_HOURS_START: '9'
          WORK_HOURS_END: '18'